version: '3.7'
services:
  db:
    cpus: "0.5"
    mem_limit: 500m
    image: postgres:15.4
    restart: always
    container_name: me-shop-postgres
    env_file: backend/.env
    ports:
      - '5432:5432'

  me-backend-app:
    cpus: "0.5"
    mem_limit: 1000m
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    container_name: me-backend-app
    env_file: backend/.env
    depends_on:
      - db
    volumes:
      - static_data:/app/static
      - media_data:/app/media
    command: sh -c "./entrypoint.sh"
    ports:
      - '80:8000'

  me-frontend-app:
    cpus: "0.5"
    mem_limit: 500m
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: me-frontend-app
    depends_on:
      - me-backend-app
    command: sh -c "npm run start"
    ports:
      - '3000:3000'
    restart: always

  nginx:
    cpus: "0.5"
    mem_limit: 500m
    image: kuzilya/misexpress_gateway:latest
    container_name: me-gateway-app
    depends_on:
      - me-backend-app
      - me-frontend-app
    ports:
      - '80:80'
      - '8800:8800'
    volumes:
      - static_data:/var/www/api/static/
      - media_data:/var/www/api/media/
    restart: always
volumes:
  static_data:
  media_data:
